## Importar librer√≠as

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Cargar datos

In [3]:
ruta = '../data/calidad_aire_2022_clean_nulos.csv'
df = pd.read_csv(ruta, delimiter=',')
df.head()

,ANO,MES,DIA,HORA,DIA_SEMANA,ESTACION,SO2,NO2,PM2.5,PM10,O3,TEMPERATURA,PRECIPITACION,DIR_VIENTO,VEL_VIENTO,ICA_SO2,ICA_PM10,ICA_O3,ICA_NO2,ICA
0,2022.0,1.0,1.0,0,Sabado,8.0,4.0,35.0,15.0,16.0,18.39,11.1,0.0,9.4,2.57,3.2,32.0,15.32,87.5,34.51
1,2022.0,1.0,1.0,1,Sabado,8.0,4.0,48.0,25.0,27.0,8.18,11.1,0.0,9.4,2.57,3.2,54.0,6.82,120.0,46.00
2,2022.0,1.0,1.0,2,Sabado,8.0,3.0,47.0,25.0,27.0,7.05,11.1,0.0,9.4,2.57,2.4,54.0,5.88,117.5,44.94
3,2022.0,1.0,1.0,3,Sabado,8.0,3.0,38.0,15.0,17.0,14.22,11.1,0.0,9.4,2.57,2.4,34.0,11.85,95.0,35.81
4,2022.0,1.0,1.0,4,Sabado,8.0,3.0,26.0,3.0,5.0,24.66,11.1,0.0,9.4,2.57,2.4,10.0,20.55,65.0,24.49